openapi: "3.0.3"
info:
  title: CadastroReservaAvaliacaoRestaurante
  version: "1.0"
  description: API de cadastro, reserva e avaliacao restaurante
servers:
  - url: http://localhost:8080
    description: Local server
tags:
  - name: AvaliacaoRestaurante
    description: Operações de avaliar e listar avaliacoes restaurante
  - name: CadastroRestaurante
    description: Operacoes de cadastros e busca Restaurante
  - name: ReservaMesa
    description: Operacooes de reservar de vaga restaurante
paths:
   /avaliacaoRestaurante:
   post:
     tags:
      - AvaliacaoRestaurante
   summary: Cria uma Avaliacao
   description: Adiciona uma nova avaliacao para o Restaurante apos o cliente visitar o mesmo
   operationId: criarAvaliacao
   requestBody:
    required: true
    content:
      application/json:
       schema:
        $ref: "#/components/schemas/CreateAvaliacao"
        responses:
           "200":
             description: OK
           "400":
             description: Bad request
           "422":
             description: Unprocessable entity
/avaliacaoRestaurante/{seqRestaurante}:
   get:
    tags:
     -AvaliacaoRestaurante
    summary: Listar Avaliacoes por restaurante
    description: Listar Avaliacoes por restaurante
    operationId: listaAvaliacoes
    parameters:
     - name: seqRestaurante
       in: path
       required: true
       schema:
        type: long
        format: int64
        example: 1
       description: ID do Parquimetro
     - name: page
       in: query 
       required: false
       schema:
        type: integer
        format: int32
        default: 0
        example: 0
       description: numero pagina
     - name: size
       in: query
       required: false
       schema:
        type: integer
        format: int32
        default: 10
        example: 10
       description: Tamanho da página
    responses:
     "200":
      description: OK
      content:
        application/json:
         schema:
           $ref: "#/components/schemas/AvaliacaoRestaurantePaginado"
/CadastroRestaurante:
       post:
         tags:
            - CadastroRestaurante
         summary: Cadastra Restaurante
         description: Cadastra um novo restaurante
         operationId: criarRestaurante
         requestBody:
          required: true
          content:
           application/json:
             schema:
              $ref: "#/components/schemas/CreateRestaurante"
         responses:
          "200":
            description: OK
          "400":
            description: Bad request
          "422":
            description: Unprocessable entity
       put:
        tags:
          - CadastroRestaurante
        summary: Atualiza restaurante 
        description: atualizaRestaurante
        operationId: atualizaRestaurantePeloId
        parameters:
         - name: id
           in: path
           required: true
           schema:
             type: integer
             format: int64
             example: 1
           description: seq Restaurante
        requestBody:
          required: true
          content:
            application/json:
             schema:
               $ref: "#/components/schemas/UpdateRestaurante"
        responses:
          "200":
           description: OK
          "400":
            description: Bad request
          "404":
             description: Not found"
          "422":
             description: Unprocessable entity
        get:
         tags:
          -CadastroRestaurante
         summary: Listar Restaurantes
         description: Listar restaurante
         operationId: listaRestaurantes
         parameters:
          - name: page
            in: query 
            required: false
            schema:
              type: integer
              format: int32
              default: 0
              example: 0
            description: numero pagina
          - name: size
            in: query
            required: false
            schema:
              type: integer
              format: int32
              default: 10
              example: 10
            description: Tamanho da página
         responses:
           "200":
           description: OK
           content:
             application/json:
              schema:
               $ref: "#/components/schemas/ListarRestaurantePaginado"
        post:
          tags:
           - CadastroRestaurante
          summary: Criar Quantitativo mesa disponivel
          description: Adiciona as mesas disponiveis para reserva
          operationId: criarQuantitativoMesaDisponivel
          requestBody:
            required: true
            content:
             application/json:
               schema:
                 $ref: "#/components/schemas/CreateQuantitativo"
          responses:
            "200":
              description: OK
            "400":
              description: Bad request
            "422":
              description: Unprocessable entity
        put:
         tags:
          - CadastroRestaurante
         summary: Atualiza a quantidade de mesas
         description: Atualiza a quantidadde de mesas 
         operationId: atualizaQuantitativoPeloId
         parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
                format: int64
                example: 1
              description: seq quantitativo
         requestBody:
           required: true
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/UpdateQuantitativo"
         responses:
           "200":
             description: OK
           "400":
             description: Bad request
           "404":
             description: Not found"
           "422":
             description: Unprocessable entity
       delete:
        tags:
          - CadastroRestaurante
        summary: Deleta um registro quantitativo mesa por ID
        description: Deleta um registro quantitativo mesa por ID
        operationId: excluiQuantitativoMesa
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
              format: int64
              example: 1
            description: ID do Quantitativo
        responses:
          "204":
            description: No content
          "400":
            description: Bad request
/ReservaMesa:	
      post:
       tags:
         - ReservaMesa
       summary: Cria Reserva
       description: Cria Reserva
       operationId: ReservaMesa
       requestBody:
         required: true
         content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReserva"
       responses:
          "200":
            description: OK
          "400":
            description: Bad request
          "422":
            description: Unprocessable entity
       put:
        tags:
          - ReservaMesa
        summary: Atualiza reserva mesa
        description: Atualiza reserva mesa
        operationId: atualizaReservaPeloId
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
              format: int64
              example: 1
            description: id reserva
        requestBody:
           required: true
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/UpdateReserva"
        responses:
           "200":
             description: OK
           "400":
             description: Bad request
           "404":
             description: Not found"
           "422":
             description: Unprocessable entity
      put:
       tags:
         - ReservaMesa
       summary: atualisa status confirmado
       description: atualisa status confirmados 
       operationId: atualisaStatusConfirmado
       parameters:
         - name: id
           in: path
           required: true
           schema:
            type: integer
            format: int64
            example: 1
           description: id reserva
      responses:
         "200":
           description: OK
         "400":
           description: Bad request
         "404":
           description: Not found"
         "422":
           description: Unprocessable entity
/ReservaMesa/{id}:
      put:
       tags:
         - ReservaMesa
       summary: atualiza Status Encerrado
       description: atualiza Status Encerrado
       operationId: atualizaStatusEncerrado
       parameters:
         - name: id
           in: path
           required: true
           schema:
            type: integer
            format: int64
            example: 1
      description: id reserva
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
        "404":
          description: Not found"
        "422":
          description: Unprocessable entity
      get:
       tags:
        -ReservaMesa
       summary: Listar Restaurantes
       description: Listar restaurante
       operationId: listaRestaurantes
       parameters:
         - name: page
           in: query 
           required: false
           schema:
            type: integer
            format: int32
            default: 0
            example: 0
           description: numero pagina
         - name: size
           in: query
           required: false
           schema:
            type: integer
            format: int32
            default: 10
            example: 10
            description: Tamanho da página
       responses:
         "200":
           description: OK
           content:
            application/json:
               schema:
                $ref: "#/components/schemas/listaReservaPaginada"
components:
  schemas:
   CreateAvaliacao:
    type: object
    properties:
      comentario:
        type: string
        example: "excelente"
        maxLength: 255
      documentoCliente:
       type: string
       example: "10254212609"
       maxLength: 255
      notaAvaliacao:
        type: number
        format: long
        example: 5
      seqRestaurante:
        type: number
        format: long
        example: 5
    required:
      - comentario
      - notaAvaliacao
      - documentoCliente
      - seqRestaurante
   schemas:
    UpdateRestaurante:
     type: object
     properties:
       tipoCozinha:
         type: string
         example: "italiana"
         maxLength: 255
       endereco:
         type: string
         example: "rua x bairro z"
         maxLength: 255
       nomeRestaurante:
          type: string
          example: "flor do mar"
          maxLength: 255
     required:
        - tipoCozinha
        - endereco
        - nomeRestaurante
    schemas:
     CreateRestaurante:
      type: object
      properties:
        tipoCozinha:
          type: string
          example: "italiana"
          maxLength: 255
        endereco:
          type: string
          example: "rua x bairro z"
          maxLength: 255
        nomeRestaurante:
          type: string
          example: "flor do mar"
          maxLength: 255
      required:
        - tipoCozinha
        - endereco
        - nomeRestaurante
     schemas:
      CreateReserva:
      type: object
      properties:
        nomeCliente:
         type: string
         example: "excelente"
         maxLength: 255
        documentoCliente:
          type: string
          example: "10254212609"
          maxLength: 255
        dataReserva:
          type: date
          format: date
          example: 15/07/2024
        seqRestaurante:
           type: number
           format: long
           example: 5
        required:
           - nomeCliente
           - dataReserva
           - documentoCliente
           - seqRestaurante
        schemas:
         UpdateReserva:
         type: object
         properties:
           dataReserva:
            type: date
            format: date
            example: 15/07/2024
           required:
             - dataReserva
      schemas:
        CreateQuantitativo:
        type: object
        properties:
          tamanhoMesa:
            type: string
            example: "4 cadeiras"
            maxLength: 255
          seqRestaurante:
           type: number
           format: long
           example: 5
          quantidadeDisponivel:
            type: number
            format: long
            example: 5
          required:
            - seqRestaurante
            - tamanhoMesa
            - quantidadeDisponivel
        schemas:
          UpdateQuantitativo:
          type: object
          properties:
             tamanhoMesa:
               type: string
               example: "4 cadeiras"
               maxLength: 255
             seqRestaurante:
                type: number
                format: long
                example: 5
             quantidadeDisponivel:
                type: number
                format: long
                example: 5
             required:
                - seqRestaurante
                - tamanhoMesa
                - quantidadeDisponivel
          schemas:
           AvaliacaoRestaurante:
           type: object
           properties:
             comentario:
               type: string
               example: "excelente"
               maxLength: 255
             documentoCliente:
                type: string
                example: "10254212609"
                maxLength: 255
             notaAvaliacao:
                type: number
                format: long
                example: 5
             seqRestaurante:
                type: number
                format: long
                example: 5
             seqAvaliacao:
                type: number
                format: long
                example: 5
             dataAvaliacao:
                 type: date
                 format: date
                 example: 15/07/2024
             required:
               - comentario
               - notaAvaliacao
               - documentoCliente
               - seqRestaurante
               - dataAvaliacao
               - seqAvaliacao
             schemas:
                Restaurante:
                type: object
                properties:
                  tipoCozinha:
                    type: string
                    example: "italiana"
                    maxLength: 255
                  endereco:
                     type: string
                     example: "rua x bairro z"
                     maxLength: 255
                  nomeRestaurante:
                       type: string
                       example: "flor do mar"
                       maxLength: 255
                  id:
                      type: number
                      format: long
                      example: 5
                  required:
                    - tipoCozinha
                    - endereco
                    - nomeRestaurante
                    - id
                schemas:
                    ReservaMesa:
                      type: object
                      properties:
                        nomeCliente:
                           type: string
                           example: "excelente"
                           maxLength: 255
                        documentoCliente:
                           type: string
                           example: "10254212609"
                           maxLength: 255
                        dataReserva:
                         type: date
                         format: date
                         example: 15/07/2024
                        seqRestaurante:
                          type: number
                          format: long
                          example: 5
                        seqReservaMesa:
                           type: number
                           format: long
                           example: 5
                        required:
                           - nomeCliente
                           - dataReserva
                           - documentoCliente
                           - seqRestaurante
                           - seqReservaMesa	  
        AvaliacaoRestaurantePaginado:
               type: object
               properties:
                  data:
                  type: array
                  items:
                     $ref: "#/components/schemas/AvaliacaoRestaurante"
                  pagination:
                       $ref: "#/components/schemas/Pagination"
        reservaMesaPaginada:
                 type: object
                 properties:
                     data:
                      type: array
                      items:
                        $ref: "#/components/schemas/ReservaMesa"
                 pagination:
                   $ref: "#/components/schemas/Pagination"
        ListarRestaurantePaginado:
                 type: object
                 properties:
                     data:
                     type: array
                     items:
                        $ref: "#/components/schemas/Restaurante"
                 pagination:
                   $ref: "#/components/schemas/Pagination"
        Pagination:
           type: object
           properties:
            page:
              type: integer
              format: int32
              example: 0
              description: Page number
              size:
               type: integer
               format: int32
               example: 10
               description: Page size
              total:
                 type: integer
                 format: int32
                 example: 100
                 description: Total number itens
              totalPages:
                 type: integer
                 format: int32
                 example: 10
                 description: Total number of pages

		